version: "3.9"

services:
  db_postgres:
    image: postgres:15
    container_name: db_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres