version: "3.9"

services:
  db_postgres:
    image: postgres:15
    container_name: db_postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

    env_file:
      - .env-non-dev