"""refresh type_item

Revision ID: 2d48af8af67d
Revises: a1d814ef5ac6
Create Date: 2023-05-13 23:27:18.060052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d48af8af67d'
down_revision = 'a1d814ef5ac6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
