"""Add relationship between item and ingredients

Revision ID: a1d814ef5ac6
Revises: 3bde0c73002d
Create Date: 2023-05-13 14:21:56.506024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d814ef5ac6'
down_revision = '3bde0c73002d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ingredient_id'), 'ingredient', ['id'], unique=False)
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.add_column('item_ingredient', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('item_ingredient', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('type_item', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('type_item', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_item', 'updated_at')
    op.drop_column('type_item', 'created_at')
    op.drop_column('item_ingredient', 'updated_at')
    op.drop_column('item_ingredient', 'created_at')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_index(op.f('ix_ingredient_id'), table_name='ingredient')
    # ### end Alembic commands ###
